# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: xenial
language: R
sudo: false
cache: packages

r:
- 3.2
- 3.3
- 3.4
- oldrel
- release
- devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

addons:
  apt:
    packages:
      libv8-dev
